# Generated by Django 3.0.7 on 2020-07-30 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('apps_settings', '0005_cartype'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashingBayPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.FloatField(blank=True, null=True)),
                ('engine', models.FloatField(blank=True, null=True)),
                ('under', models.FloatField(blank=True, null=True)),
                ('inside', models.FloatField(blank=True, null=True)),
                ('blowing', models.FloatField(blank=True, null=True)),
                ('hoover', models.FloatField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_settings.CarType')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyProfile')),
            ],
        ),
    ]
