# Generated by Django 3.0.7 on 2020-08-03 03:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_settings', '0005_cartype'),
        ('company', '0001_initial'),
        ('washing_bay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashingBaySales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2020, 8, 3))),
                ('registration_number', models.CharField(max_length=20)),
                ('body', models.BooleanField(default=False)),
                ('engine', models.BooleanField(default=False)),
                ('under', models.BooleanField(default=False)),
                ('inside', models.BooleanField(default=False)),
                ('blowing', models.BooleanField(default=False)),
                ('hoover', models.BooleanField(default=False)),
                ('amount', models.FloatField(default=0.0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_settings.Employee')),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_settings.CarType')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyProfile')),
            ],
        ),
    ]
