# Generated by Django 3.0.7 on 2020-08-03 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washing_bay', '0002_washingbaysales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='washingbaysales',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
